# Generated by Django 2.0.7 on 2018-07-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20180708_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='author',
        ),
    ]
